version: 2

sources:
  - name: finance
    schema: "{{ env_var('SNOWSQL_SCHEMA') }}"
    tables:
      - name: TRANSACTIONS
        freshness: # default freshness
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        loaded_at_field: _snowflake_loaded_at